### ISSUE TITLE
AD B2C Custom Policy Support

### ISSUE THREAD

**Issue by niTrekker3267** [Earlybyte/aad_oauth#104]
Hi,
Does this work with AD B2C Custom Policies?
I am trying to use this with custom policies but I am getting the following errors - 
E/flutter (12699): #0      AadOAuth._performFullAuthFlow (package:aad_oauth/aad_oauth.dart:80:7)
E/flutter (12699): <asynchronous suspension>
E/flutter (12699): #1      AadOAuth._authorization (package:aad_oauth/aad_oauth.dart:69:15)
E/flutter (12699): <asynchronous suspension>
E/flutter (12699): #2      AadOAuth.login (package:aad_oauth/aad_oauth.dart:39:5)
E/flutter (12699): <asynchronous suspension>

**Comment by jacojvv-dev** [comment]
Hi @niTrekker3267 it does support custom B2C Policies - assuming they are working correctly. I am not a maintainer of this library - but I do use custom B2C policies in an app I am working on - so I'll share my setup with you so that you can verify it against your own configuration.

*Take note that the readme is wrong, scope is not simply 'YOUR_CLIENT_ID offline_access'!*

```dart
static final Config _config = new Config(
  tenant: 'AAD_TENANT_NAME', // e.g. contoso
  clientId: 'AAD_CLIENT_ID', // e.g. f96836d7-cc3e-46f3-a9b8-b06c16b9a1a7
  scope: "AAD_SCOPE offline_access", // e.g. https://contoso.onmicrosoft.com/f17b7ce1-f79a-4352-81d7-1d6d63b76042/api offline_acccess
  redirectUri: "https://login.live.com/oauth20_desktop.srf",
  isB2C: true,
  policy: 'AAD_POLICY', // e.g. B2C_1A_SignUpWithPhoneSignInWithPhoneOrEmail
  tokenIdentifier: 'AAD_TOKEN_IDENTIFIER', // this can be whatever you want - it's just a key that the library uses to store tokens
);
```

I am running version 0.2.0 of aad_oauth as 0.2.1 introduced an issue that I am still waiting for feedback from the authors on.

I  based my B2C policies very closely on policies that I have on my GitHub page [here](https://github.com/jacojvv-dev/Azure-B2C-Sign-Up-With-Phone-Sign-In-With-Phone-Or-Email).

Also ensure that your application is set up correctly on B2C - instructions for this are in the readme.
