### ISSUE TITLE
migrate from flutter_webview_plugin to webview_flutter

### ISSUE THREAD

**Issue by explorova** [Earlybyte/aad_oauth#124]
flutter_webview_plugin is about to be deprecated, need to migrate the dependecy to the new webview_flutter plugin, per the notice here: https://pub.dev/packages/flutter_webview_plugin

**Comment by shubham-vunet** [comment]
+1

**Comment by RoarGronmo** [comment]
The complete errormessage says this:
```The plugin `flutter_webview_plugin` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.```

**Comment by Saurabhkumar1989** [comment]
Any update to this issue. As this plugin may stop working shortly.

The error message :

The plugin `flutter_webview_plugin` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if this plugin supports the Android V2 embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by dreamflasher** [comment]
I hate stale bots. This issue is relevant, please reopen.
