### ISSUE TITLE
How to use default browser for sign in Mobile

### ISSUE THREAD

**Issue by Harshk16** [Earlybyte/aad_oauth#152]
1.  Package is opening web view for login. user has to make login every time even user is logged in default browser.
2.  Two Factor authenticate is not working with login (seems like because of web view it's not letting to navigate in Authenticator app)

**Comment by gustavobigardi** [comment]
I'm facing the same issue with the item 2 here. The MFA is enabled for users on Azure AD, it works on flutter Web but with mobile devices, it just asks for user + password and nothing about the MFA, it just goes ahead and continue with the flow... And I noticed that in the flutter web, the authentication is opened in a "popup" window, since mobile is in an embeded browser...

**Comment by Harshk16** [comment]
@gustavobigardi i think if we use default browser (like chrome and safari) then it will fix these issue

**Comment by gustavobigardi** [comment]
But when asking for some scopes, like Mail.Read from the Ms Graph, it asks for the MFA on Mobile and Web, but only requesting basic scopes like user.read and others, it only asks for the MFA only on Web.

If the problem is the webview, why it asks with the Mail.Read scope?
