### ISSUE TITLE
Add a way to check if the user is already logged in

### ISSUE THREAD

**Issue by Zazo032** [Earlybyte/aad_oauth#209]
In the past, for Flutter Web B2C, checking if the user was not logged in was not trivial, so I added a `isLogged` getter to my fork. I saw that recently Flutter Web B2C support was added, so I think it could be useful to add that change to the parent plugin too, so we can get rid of my [fork](https://github.com/Zazo032/aad_oauth/commit/8fc1f0808ebb2da21e37e4cc89228e46521d9c4d).

It's a long commit with unrelated changes, before opening a PR, does this addition make sense in the current state of the plugin? Or is there any proper way to check if the user is logged in?

**Comment by Zazo032** [comment]
For extra context: in our web app, we guard certain routes from unlogged users, so if a user tries to access `webapp.com/profile` while it's not logged in, we redirect the user to `webapp.com/login?redirect=/profile`, where he logs in and then he is redirected to his profile. However, if the user was already logged in and viewing his profile, but he refreshes the web app, `getAccessToken()` returns `null` so we can't check if we was already logged in. For that, I modified the `msalv2.js` file, to add `getAccount()` and `isLogged()` methods like this:

```js
function getAccount() {
  const currentAccounts = myMSALObj.getAllAccounts();

  if (currentAccounts === null || currentAccounts.length === 0) {
    return;
  } else if (currentAccounts.length > 1) {
    // Multiple users - pick the first one, but this shouldn't happen
    console.warn("Multiple accounts detected, selecting first.");

    return currentAccounts[0];
  } else if (currentAccounts.length === 1) {
    return currentAccounts[0];
  }
}

function isLogged() {
  return getAccount() !== undefined;
}
```

With that, we know that the user has some auth data on the browser, and we just refresh the token for him:

```dart
Future<void> initialize() {
  instance.aad = AadOauth(...);
  if (await instance.aad.isLogged) {
    // Refresh token
  }
}
```

**Comment by stevenebutler** [comment]
I've had a think about this and given my understanding, having an access token doesn't necessarily mean you are still logged in.
1. The access token may be expired (likely)
2. The refresh token may no longer be valid (less likely)

My understanding is there's no way to know if the refresh token will work without actually trying to use it to acquire a new access token. When you check isLogged, it will probably work, but if it doesn't, do you also have some fallback code to handle the case where the refresh token no longer works? In the same vein, do you even need to use the refresh token in the common case that the access token is still valid? Why refresh the token if you don't need to? Of course, even though the access token may still say it's not expired, there's nothing stopping the end point from rejecting it (e.g. clock skew between the client and server) so you would have to be prepared for that eventuality as well.

Anyway, I have built my app against your fork and didn't have any issues (as I expected, but wanted to be sure), so it doesn't break anything that I'm using it for. If it works for your use case then that's great and it shouldn't cause any harm to existing functionality.

In general, I'm interested in your thoughts on the state of the web support in aad_oauth because it has a number of issues that would be nice to resolve.

On mobile, you can just call login to get the token because if it's not valid the oauth library automatically pushes a new route onto the flutter stack with the login window. On the web it's either going to redirect the whole page to oauth (if using redirect flow) or continue to show the current route, but popup a new authorization window. When using popups I can see how redirecting to another view might be handy here if you don't want to render a page that makes no sense until the user is logged in.

This is effectively what redirect flow does, but it has the ugly side effect of killing the flutter app entirely while the login is happening, so you will typically lose all your state (unless you save it somewhere) when you start the login redirect flow.

In my app, I use redirect flow because when the flutter web app is installed as a PWA on an iOS device the popup window used by MSAL is unable to be monitored by the MSAL js library in the main window because the popup is activated in a regular Safari browser window, rather than the PWA context and is thus isolated from the PWA. You can post the token back to the parent, but I wasn't able to find a way to get that information back into MSAL.

The redirect flow isn't a big deal for me because the user must always be logged in to use the app so the first thing the app does when started is call login - if they've just logged in it won't redirect, and if they haven't it will redirect to the login screen before the user has changed any state in the app.

I've also not been able to get the latest version of the MSAL library to work with redirect flow. I'm not sure what the issue is but it seems to cause problems with the flutter navigator so support is stuck with the current version.

Naturally, none of this is ideal for other use cases such as yours so I'm very interested in ideas that could improve the web experience. I have contemplated ditching MSAL directly and making more use of the existing mobile code for refresh token handling which would allow the use of popups even within iOS PWAs (by using postMessage) - that way the state of the app would be retained while the user logs in, in the normal case (naturally if they refreshed the window or something it would probably fail in some odd way). 

The main reasons I haven't gone down this path are it's very time consuming to trial different approaches when interoperating with flutter/dart/js so big investment to trial things and fear of having to change the APIs leading to differences between mobile and web versions of aad_oauth.

Apologies for the length of this reply and taking your issue off on a bit of a tangent.

**Comment by Zazo032** [comment]
We're using the popup instead of redirect in our implementation, so we can keep the previous path after logging in. However, I noticed a behaviour change in our mobile app:

If you call `login` on the app, without internet connection, my fork just returned `null` or an empty string, but now it tries to load the tenant url:
![image](https://user-images.githubusercontent.com/2807712/217238708-721b677a-e9cd-4b2d-b65b-f960689f6533.png)
Could this be fixed so that, if there's no internet connection, no error login page is shown? Or could it be related to the `login(refreshIfAvailable: true)` param?

**Comment by tigloo** [comment]
We have implemented a method like this to determine if we need a new token:

```dart
bool _isValidToken(final String? token) {
    if (token == null) {
      return false;
    }
    try {
      final decodedToken = JwtDecoder.decode(token);
      final expi = Instant.unixEpoch.add(Time(seconds: decodedToken['exp']));
      final nbfi = Instant.unixEpoch.add(Time(seconds: decodedToken['nbf']));
      final now = Instant.now();
      return now.isAfter(nbfi) && now.isBefore(expi);
    } catch (e) {
      return false;
    }
  }
```

If this method returns false, we need to call getAccessToken() to refresh the session, if that one then also fails, we know that we are not logged in.

Based on this, I think what you are trying to achieve can be implemented entirely on the Dart side of the plugin.

**Comment by OssiPesonen** [comment]
I would personally like a method that would check access token expiration and do a refresh on that token automatically, much like Auth0 SDK does with `getAccessTokenSilently()`. This way the responsibility of handling expiration and doing a refresh would not be left to the client.

**Comment by AndreasHassing** [comment]
Somewhat similar to @tigloo, I'm currently doing:

*jwt_utils.dart*:
```dart
import 'package:jwt_decoder/jwt_decoder.dart';

class JwtUtils {
  static ({String token, Map<String, dynamic> map}) _lastValue =
      (token: '', map: {});

  static DateTime getExpUtc(String token) =>
      DateTime.fromMillisecondsSinceEpoch((decodeM(token)['exp'] as int) * 1000,
          isUtc: true);

  static Map<String, dynamic> decodeM(String token) {
    final value = _lastValue.token == token
        ? _lastValue
        : _lastValue = (token: token, map: JwtDecoder.decode(token));

    return value.map;
  }
}
```

*main.dart*:
```dart
extension AddGetAccessTokenSilently on AadOAuth {
  Future<String?> getAccessTokenSilently() async {
    final accessToken = await getAccessToken();

    final DateTime expiresAt =
        accessToken != null ? JwtUtils.getExpUtc(accessToken) : DateTime(0);

    final utcNow = DateTime.now().toUtc();

    final isExpired = expiresAt.isBefore(utcNow);
    final isExpiringSoon = expiresAt.isBefore(utcNow.add(5.minutes));

    if (isExpired || isExpiringSoon) {
      final result = await login(refreshIfAvailable: true);

      return result.fold(
        (failure) =>
            isExpiringSoon ? accessToken : throw Exception(failure.toString()),
        (token) => token.accessToken,
      );
    }

    return accessToken;
  }
}

extension on int {
  Duration get minutes => Duration(minutes: this);
}
```
