### ISSUE TITLE
 Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by amirsuwal01** [Earlybyte/aad_oauth#225]
```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      RequestCode.requestCode (package:aad_oauth/request_code.dart:39:44)
<asynchronous suspension>
#1      MobileOAuth._performFullAuthFlow (package:aad_oauth/helper/mobile_oauth.dart:108:16)
<asynchronous suspension>
#2      MobileOAuth._authorization (package:aad_oauth/helper/mobile_oauth.dart:91:22)
<asynchronous suspension>
#3      MobileOAuth.login (package:aad_oauth/helper/mobile_oauth.dart:38:12)
<asynchronous suspension>
```

i have added
final navKey = GlobalKey<NavigatorState>();

Added navkey both inside  Materialapp and also in config

I am using auto_route that has navigationkey as well

**Comment by tmmr10** [comment]
I faced the same issue because I created the navkey twice.
Just create it once on the top of the _main.app_
`final navigatorKey = GlobalKey<NavigatorState>();` and use the same `navigatorKey` for
_MaterialApp_:
`return MaterialApp(
      title: 'Title',
      theme: ...,
      home: ...,
      navigatorKey: navigatorKey,
    );`
and _Config_:
```
final Config config = Config(
        tenant: ...,
        clientId: ...,
        scope: ...,
        navigatorKey: navigatorKey);
```
in my case the materialApp and the config are in a different file. Just import the navigatorKey for the config from the _main.app_
