### ISSUE TITLE
Please upgrade dependency on `flutter_lints` to `3.0.0`

### ISSUE THREAD

**Issue by RoarGronmo** [Earlybyte/aad_oauth#275]
Just ran a check on which dependency stoppped upgrading `flutter_lints` dependency to `3.0.0`.

It gave me following result: 

```
C:\Flutter\flutter\bin\flutter.bat --no-color pub get
Resolving dependencies...
Because flutter_lints >=3.0.0 depends on lints ^3.0.0 and aad_oauth 1.0.0 depends on lints ^2.1.1, flutter_lints >=3.0.0 is incompatible with aad_oauth 1.0.0.
And because no versions of aad_oauth match >1.0.0 <2.0.0, flutter_lints >=3.0.0 is incompatible with aad_oauth ^1.0.0.
So, because mwork depends on both aad_oauth ^1.0.0 and flutter_lints ^3.0.0, version solving failed.


You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on flutter_lints: flutter pub add dev:flutter_lints:^2.0.3
Process finished with exit code 1
```

Could you please upgrade your dependency to use `3.0.0` or higher of `flutter_lints` library ?

**Comment by mikedigit** [comment]
This package is starting to be the most used package for aad authentification.

In order to prevent conflict for user, rather than just updating a dependency, I think we should try to remove as much dependencies as possible.

A package like flutter_lints is easily inlinable by just taking the lint rules and adding them to the analysis_options.yaml.

**Comment by MohamedHusseinIOS** [comment]
any updates for this issue ?

**Comment by mikedigit** [comment]
Yes this has been merged into master here: https://github.com/Earlybyte/aad_oauth/pull/279 and should be closed.
